### ISSUE TITLE
Unable to switch default sim slot

### ISSUE THREAD

**Issue by nighthawk149** [Moyster/android_device_meizu_m2note#23]
Sim 2 + Sd card users can only use gsm mode.
It is not a hardware limitation! Original Flyme OS has an option to switch default sim card for data.

**Comment by Moyster** [comment]
> Data on second sim **in a dual-sim** configuration. (hardware limitation)

Hello,
http://forum.xda-developers.com/showpost.php?p=68897682&postcount=384

I'm not gonna quote all answers that say sim +sdcard works fine, but that was done using the keyword "simcard" in the search field.

**Comment by nighthawk149** [comment]
At myself am fixed that by:

- flashing clean stock Flyme OS with sp flash tool
- wait for bootup with sim card installed into slot 2
- flash preloader and twrp for CM with sp flash tool
- flash latest CM build with twrp
- ensure that sim2 can be used for "3g" and "4g" networks
- ... PROFIT!!!!

Before that i cannot use sim2 for other than GSM notworks.
Maybe that helps for other users with that problem.

**Comment by Moyster** [comment]
> ... PROFIT!!!!
I love that reference :smile: 

I read somewhere you could try putting the sim in the slot you dont want, selecting "2g only" for that slot in the Settings, putting the sim back in the wanted slot and selecting "lte/3g" would work.
It was for another phone but for cm-12.1 on mt6753 SoC, so who knows :)

Glad it's fixed for you ;)

**Comment by Gargarospo** [comment]
Just for the records...
I was living that situation: 3G or more only in SIM1, while SIM2 could connect only with 2G.
So I tried to flash Flyme OS, bootup with both SIM cards inserted. I could connect to 3G/4G with both SIM's, so I reflashed CM 12.1 RC1 and now the situation is the opposite: SIM1 > 2G only, SIM2 3G/4G.

**Comment by Moyster** [comment]
To add a bit of "technical details" instead of simply saying "the mtk ril in cm-12.1 lacks a few stuff" it seems we lack the code to to properly switch the data stack from one sim to another, long story short the first sim listed by the baseband/modem/whatever (which is the active "data" sim then) is assumed to be the sim with data (by cm-12.1)
cm12/frameworks/opt/telephony/src/java/com/android/internal/telephony/MediaTekRIL.java :
```
    // TODO: Support multiSIM
    // Sim IDs are 0 / 1
    int mSimId = 0;
```
(patch is here : https://github.com/Moyster/android_device_mt6753_common/blob/cm-12.1/patches/framework_opt_telephony/0001-Update-for-mtk.patch )

**Comment by Moyster** [comment]
not exactly a "proper solution" but that should help if 3rd party softwares can't change default sim (look for "mediatek sim switch" on the playstore ;) )
