### ISSUE TITLE
SIM card not recognised during first boot

### ISSUE THREAD

**Issue by hellenicsun** [Moyster/android_device_meizu_m2note#35]
During ROM's initial boot where one setups the phone, SIM is not recognised. It's a problem if someone has SMS verification for a Google account.

An immediate restart solves the issue.

**Comment by Moyster** [comment]
Hello,  
  
Actually it seem to be more random than that, some phones have simcard recognized at first, some don't.
If you come from flyme, the sim that had data will be the same under CM, see : https://github.com/Moyster/android_device_meizu_m2note/issues/23  
  
Solutions :   
- reboot if sim is not detected  
- Flashing Gapps after the first boot works too  

Considering cm-12.1 / lp is pretty aging and meizu will release flyme 6 (mystery remains about if it'll be LP or MM based)
and considering the sim/ril support got a bit better in MM/N, I'll probably not look into this (it's not really impacting users).

(PS: I'm gonna edit all previously closed issues to add tags if the issue was solved, so people looking at closed issue can more easily finds quick fix / solutions to all these small quirks ;) )

**Comment by mbskykill** [comment]
the flyme 6 is mm based

**Comment by Moyster** [comment]
We'll see if Meizu decided to keep up their promises or if they just decided they wanted a shit storm and everyone to advertise them negatively.  
  
Sad to see Meizu will probably ship a lollipop flyme 6 version and goes like "we didn't lie, we've got you flyme 6".  
  
It legit makes no sense to destroy the confidence their users put into them, me included, but whatever they thought was "smart" is going to cost them money (from everyone running away, feeling betrayed).

@meizuosc why did you guys do this ? You were the chosen one, anakin !

**Comment by hellenicsun** [comment]
..and we all know what happened with Anakin

**Comment by mbskykill** [comment]
i  can share the flyme6  rom .   do  you need this  rom   if  i can upload  mega.

**Comment by Moyster** [comment]
Unless it's a new beta, I think I was amongst the first to get my hands on  the CBT release ;)
